<a href="https://colab.research.google.com/github/vikramvundyala/python_AI-ML/blob/main/U2_MH1_AuthorIdentification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Problem Statement

The problem is to identify the author of a  book from a given list of possible authors.

## Learning Objectives

At the end of the experiment, you will be able to:

* Use NLTK package
* Extract handcrafted features
* Preprocess the text
* Write an algorithm to identify the author of a given book

In [ ]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="854" height="480" controls>
  <source src="https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/Walkthrough/authoridentification.mp4" type="video/mp4">
</video>
""")

## Background

Author identification is the task of identifying the author of a given text. It can be considered as a typical classification problem, where a set of books with known authors are used for training. The aim is to automatically determine the corresponding author of an anonymous text.

## Grading = 10 Marks

## Setup Steps

In [14]:
#@title Run this cell to complete the setup for this Notebook

from IPython import get_ipython
ipython = get_ipython()

notebook="U2_MH1_AuthorIdentification" #name of the notebook
Answer = "This notebook is graded by mentors on the day of hackathon"
def setup():
    ipython.magic("sx wget https://cdn.talentsprint.com/talentsprint1/archives/sc/aiml/experiment_related_data/AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.rar")
    ipython.magic("sx unrar e /content/AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.rar")
    print ("Setup completed successfully")
    return

setup()

Setup completed successfully

### NOTE: You are allowed to use ML libraries such as Sklearn, NLTK, etc wherever applicable

### Downloading the required nltk Packages before moving ahead

In [15]:
import nltk
nltk.download('gutenberg')
nltk.download('punkt')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## **Stage 1:** Dataset Preparation

### 1 Marks -> Ensure you appropriately split the multiple short stories for the below-mentioned authors, Which will be your training data.

**1.** Before moving ahead choose two authors based on your team-number allocation: <br/>


Team=1,5,9,13,17,21,25,29  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Author-A Vs Author-B <br />
Team=2,6,10,14,18,22,26,30 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Author-B Vs Author-C <br />
Team=3,7,11,15,19,23,27,31 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Author-C Vs Author-D <br />
Team=4,8,12,16,20,24,28,32 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           Author-D Vs Author-E <br />



**2.** Link to the short stories collection of each author for your problem: <br />

*   Author-A -> Rudyard Kipling   [Short Stories Collection](http://www.gutenberg.org/files/2781/2781-0.txt) &nbsp;&nbsp;
*   Author-B -> Anton Chekhov [Short Stories Collection](http://www.gutenberg.org/files/1732/1732-0.txt) &nbsp;&nbsp;
*   Author-C -> Guy De Maupassant [Short Stories Collection](http://www.gutenberg.org/cache/epub/21327/pg21327.txt)&nbsp;&nbsp;
*   Author-D -> Mark Twain [Short Stories Collection](http://www.gutenberg.org/files/245/245-0.txt)&nbsp;&nbsp;
*   Author-E -> Saki [Short Stories Collection](http://www.gutenberg.org/files/1477/1477-0.txt)&nbsp;&nbsp;

**Hint for downloading raw text from Gutenberg :**  Refer to the section "Electronic Books" in the following  [link](https://www.nltk.org/book/ch03.html) for the instructions.



**Hint for finding the index of a text:**   You may use `raw.find()` and `raw.rfind()` in the same [link](https://www.nltk.org/book/ch03.html) to find the appropriate index of the start and end location

**Hint for splitting the multiple stories:** Split the stories using long space (white space character)

**Note:** Ignore the table of contents section from the given stories

In [16]:
# YOUR CODE HERE for downloading and splitting the multiple stories of respective authors which are allocated to you

from urllib import request
from nltk.tokenize import sent_tokenize
import re
import pandas as pd

url = "https://www.gutenberg.org/files/2781/2781-0.txt"
response = request.urlopen(url)
raw_A = response.read().decode('utf8')

text_split_A = re.split(r'[\r\n\r\n\r\n\r\n\r\n]', raw_A)
len(text_split_A)
df = pd.DataFrame({'Paragraphs': [para.strip() for para in text_split_A if para.strip() != '']})
stories_list_A = df.iloc[17:29]

In [17]:
stories_list_A

                           Paragraphs
17       HOW THE WHALE GOT HIS THROAT
18         HOW THE CAMEL GOT HIS HUMP
19    HOW THE RHINOCEROS GOT HIS SKIN
20      HOW THE LEOPARD GOT HIS SPOTS
21               THE ELEPHANT’S CHILD
22  THE SING-SONG OF OLD MAN KANGAROO
23    THE BEGINNING OF THE ARMADILLOS
24   HOW THE FIRST LETTER WAS WRITTEN
25          HOW THE ALPHABET WAS MADE
26  THE CRAB THAT PLAYED WITH THE SEA
27     THE CAT THAT WALKED BY HIMSELF
28         THE BUTTERFLY THAT STAMPED

In [18]:
story_Array = []
i =29;
for outer_idx, outer_row in df.iloc[17:29].iterrows():
    story_chunk = []
    for inner_idx, inner_row in df.iloc[i:].iterrows():
        if outer_row["Paragraphs"].strip() == inner_row["Paragraphs"].strip():
            break
        story_chunk.append(inner_row["Paragraphs"])
        i += 1
    if(len(story_chunk)>0):
     story_Array.append(" ".join(story_chunk))

df_A = pd.DataFrame({'Story': [s for s in story_Array if s != '']})
df_A['Author'] = 'Rudyard Kipling'

In [19]:
url_1 = "https://www.gutenberg.org/files/1732/1732-0.txt"
response_B = request.urlopen(url_1)
raw_B = response_B.read().decode('utf8')

text_split_B = re.split(r'[\r\n\r\n\r\n\r\n\r\n]', raw_B)
len(text_split_B)
df_1 = pd.DataFrame({'Paragraphs': [para.strip() for para in text_split_B if para.strip() != '']})

In [20]:
df_1.iloc[17:38]
story_Array_B = []
i =38;
for outer_idx, outer_row in df_1.iloc[17:38].iterrows():
    story_chunk = []
    for inner_idx, inner_row in df_1.iloc[i:].iterrows():
        if outer_row["Paragraphs"].strip() == inner_row["Paragraphs"].strip():
            break
        story_chunk.append(inner_row["Paragraphs"])
        i += 1
    if(len(story_chunk)>0):
     story_Array_B.append(" ".join(story_chunk))

len(story_Array_B)
df_B = pd.DataFrame({'Story': [s for s in story_Array_B if s != '']})
df_B['Author'] = 'Anton Chekhov'
df_B.head()

                                               Story         Author
0  THE SCHOOLMISTRESS AT half-past eight they dro...  Anton Chekhov
1  A NERVOUS BREAKDOWN A MEDICAL student called M...  Anton Chekhov
2  MISERY “To whom shall I tell my grief?” THE tw...  Anton Chekhov
3  CHAMPAGNE A WAYFARER’S STORY IN the year in wh...  Anton Chekhov
4  AFTER THE THEATRE NADYA ZELENIN had just come ...  Anton Chekhov

In [26]:
df_All = pd.concat([df_A, df_B], axis=0, ignore_index=True)

In [27]:
df_All.head()

                                               Story           Author
0  HOW THE WHALE GOT HIS THROAT IN the sea, once ...  Rudyard Kipling
1  HOW THE CAMEL GOT HIS HUMP NOW this is the nex...  Rudyard Kipling
2  HOW THE RHINOCEROS GOT HIS SKIN ONCE upon a ti...  Rudyard Kipling
3  HOW THE LEOPARD GOT HIS SPOTS IN the days when...  Rudyard Kipling
4  THE ELEPHANT’S CHILD IN the High and Far-Off T...  Rudyard Kipling

## **Stage 2**: Experiment with Handcrafted features representation
Extract Handcrafted features for the obtained short stories from **Stage-1**

**Stylometry:**

Each person has a unique vocabulary, sometimes rich, sometimes limited. Although a larger vocabulary is usually associated with literary quality, this is not always the case. Ernest Hemingway is famous for using a surprisingly small number of different words in his writing, which did not prevent him from winning the Nobel Prize for Literature in 1954.

Some people write in short sentences, while others prefer long blocks of text consisting of many clauses. No two people use semicolons, em-dashes, and other forms of punctuation in the same way.




**You may explore the following ways to analyze the text and generate handcrafted features by searching text in a probing way:**

a)  Could the style of punctuation usage help as a handcrafted feature? Both by those who follow punctuations and by those who don't? Interesting [link](https://qwiklit.com/2014/03/05/top-10-authors-who-ignored-the-basic-rules-of-punctuation/)

b) The same word can sometimes be used in different contexts repeatedly by different authors. Could this fact be converted as a handcrafted feature? [link](https://www.nltk.org/book/ch01.html)

c) The above two are merely examples; As you might have noticed already the NLTK book [link](https://www.nltk.org/book/) offers several methods of analyzing and understanding the text. Each of these analyses is in itself capable of being a handcrafted feature. **However for your evaluation a minimal set of useful handcrafted features which is helping you prove a classification of an is sufficient**

d) Could most common words be used to distinguish authors?  Refer "Counting Vocabulary" section of the [link](https://www.nltk.org/book/ch01.html)

e) How about using a count of most frequently used bi-gram, tri-grams, and using it to classify an author?

f) How about using the frequency histogram of the most frequently used words across the stories by a given author a useful feature?

The limit here is endlessly limited only by your imagination, and of course your accuracy! :)

### 1 Marks ->  a) List 6 handcrafted features to distinguish author stories.

In [28]:
# For eg:
# 1. UniqueWords
# 2. AvgSentLength
# List the other handcrafted features here
import nltk
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

nltk.download('punkt', force=True)
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('all')

stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)
lemmatizer = WordNetLemmatizer()

def get_word_pos(treebank_tag):
  if treebank_tag.startswith('J'):
    return nltk.corpus.wordnet.ADJ
  elif treebank_tag.startswith('V'):
    return nltk.corpus.wordnet.VERB
  elif treebank_tag.startswith('N'):
    return nltk.corpus.wordnet.NOUN
  elif treebank_tag.startswith('R'):
    return nltk.corpus.wordnet.ADV
  else:
    return nltk.corpus.wordnet.NOUN

def clean_text(text: str) :
  words = word_tokenize(text)
  words = [word.lower() for word in words if word.isalpha()]
  words = [word for word in words if word not in stop_words]
  words = [word for word in words if word not in punctuation]
  pos_tags = nltk.pos_tag(words)
  lemmatized_tokens = [lemmatizer.lemmatize(word, get_word_pos(pos_tag)) for word,pos_tag in pos_tags]
  return lemmatized_tokens

def adverb_count(text: str) -> int:
  words = word_tokenize(text)
  pos_tags = nltk.pos_tag(words)

  # Tags for adverbs in Penn Treebank POS tagging
  adverb_tags = ['RB', 'RBR', 'RBS']
  return sum(1 for word, tag in pos_tags if tag in adverb_tags)

def adjective_count(text: str) -> int:
  words = word_tokenize(text)
  pos_tags = nltk.pos_tag(words)

  # Tags for adverbs in Penn Treebank POS tagging
  adverb_tags = ['RB', 'RBR', 'RBS']
  return sum(1 for word, tag in pos_tags if tag in adverb_tags)

def adjective_count(text: str) -> int:
  words = word_tokenize(text)
  pos_tags = nltk.pos_tag(words)

  # Tags for adjectives: JJ (regular), JJR (comparative), JJS (superlative)
  adjective_tags = ['JJ', 'JJR', 'JJS']
  return sum(1 for word, tag in pos_tags if tag in adjective_tags)

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

def test_models(X, y):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
  model1 = DecisionTreeClassifier()
  model2 = KNeighborsClassifier(n_neighbors=8)
  model3 = SGDClassifier()
  model4 = SVC(kernel='linear')
  model5 = LogisticRegression()
  model6 = Perceptron(max_iter=1000, eta0=1.0, random_state=0)

  models = [model1, model2, model3, model4, model5, model6]
  model_stats = []
  for model in models:
      model.fit(X_train, y_train)         # fit the model
      y_pred= model.predict(X_test)       # then predict on the test set
      accuracy= accuracy_score(y_test, y_pred)
      accuracy_train = accuracy_score(y_train, model.predict(X_train))
      model_stats.append( f"Accuracy(in %): {model} Train Accuracy {accuracy_train}  Test Accuracy {accuracy}")
  return model_stats

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package mock_corpus to /root/nltk_data...
[nltk_data]    |   Package mock_corpus is already up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Package wordnet2022 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection all

In [29]:

df_All['no_of_sentences'] = df_All['Story'].apply(lambda x: len(sent_tokenize(x)))
df_All['clean_text'] = df_All['Story'].apply(lambda x: clean_text(x))

df_All['adverb_count'] = df_All['Story'].apply(lambda x: adverb_count(x))
df_All['adjective_count'] = df_All['Story'].apply(lambda x: adjective_count(x))


# df["vocab_richness"] = df["clean_text"].apply(
#     lambda text: len(set(word_tokenize(text.lower()))) / len(word_tokenize(text))
# )
df_All['unique_word_length'] = df_All['clean_text'].apply(lambda x: len(x))
df_All['avg_sentence_length'] = df_All['unique_word_length']/df_All['no_of_sentences']
df_All.head()

,Story,Author,no_of_sentences,clean_text,adverb_count,adjective_count,unique_word_length,avg_sentence_length
0,"HOW THE WHALE GOT HIS THROAT IN the sea, once ...",Rudyard Kipling,34,"[whale, get, throat, sea, upon, time, best, be...",58,64,443,13.029412
1,HOW THE CAMEL GOT HIS HUMP NOW this is the nex...,Rudyard Kipling,36,"[camel, get, hump, next, tale, tell, camel, ge...",65,79,452,12.555556
2,HOW THE RHINOCEROS GOT HIS SKIN ONCE upon a ti...,Rudyard Kipling,34,"[rhinoceros, get, skin, upon, time, uninhabite...",52,45,376,11.058824
3,HOW THE LEOPARD GOT HIS SPOTS IN the days when...,Rudyard Kipling,94,"[leopard, get, spots, day, everybody, start, f...",127,218,947,10.074468
4,THE ELEPHANT’S CHILD IN the High and Far-Off T...,Rudyard Kipling,78,"[elephant, child, high, time, elephant, best, ...",155,238,1126,14.435897

###  2 Marks -> b) Write functions for any 4 of the above 6 handcrafted features and label your authors accordingly.

- Get any 4 hand crafted features from the above listed 6 hand-crafted features for every story obtained from **stage-1**.
- Identify your target variable as an author and label them accordingly.

In [30]:
# Stories_list    UniqueWords    AvgSentLength     Label
#     1               x1               x2            y
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


X = df_All[["unique_word_length", "avg_sentence_length","no_of_sentences", "adverb_count", "adjective_count"]].copy()
y = df_All['Author']

labelEncoder = LabelEncoder()
y = labelEncoder.fit_transform(y)


print('-------------Handcrafted Features------------------------')
handcrafted_stats = test_models(X, y)
for stat in handcrafted_stats:
  print(stat)


# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# model = LogisticRegression()
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)
# print(accuracy_score(y_test, y_pred))

# YOUR CODE HERE

-------------Handcrafted Features------------------------
Accuracy(in %): DecisionTreeClassifier() Train Accuracy 1.0  Test Accuracy 0.7142857142857143
Accuracy(in %): KNeighborsClassifier(n_neighbors=8) Train Accuracy 0.625  Test Accuracy 0.7142857142857143
Accuracy(in %): SGDClassifier() Train Accuracy 0.625  Test Accuracy 0.7142857142857143
Accuracy(in %): SVC(kernel='linear') Train Accuracy 1.0  Test Accuracy 0.5714285714285714
Accuracy(in %): LogisticRegression() Train Accuracy 1.0  Test Accuracy 0.5714285714285714
Accuracy(in %): Perceptron() Train Accuracy 0.625  Test Accuracy 0.7142857142857143

##**Stage 3:** Experiment with Text processing and representation:
Extract features using TFIDF or CountVectorizer or Word2vec for the obtained short stories from **Stage-1**

### 1 Mark -> a) Performing basic cleanup operations such as removing the newline characters and removing trailing spaces

**For example,** Your sentence looks as follows \[' This is a sentence\n\r. Another sentence \n'].

After newline removal from the above example, your sentence will look like \['This is a sentence. Another sentence'].

 In order to do this, you can try using a combination of split() and join()

In [57]:
# YOUR CODE HERE

df_All['clean_msg'] = df_All['clean_text'].apply(lambda x: ' '.join(x))

df_All['clean_msg'] = df_All['clean_msg'].replace('\n', ' ', regex=True)
df_All['clean_msg'] = df_All['clean_msg'].replace('\r', ' ', regex=True)
df_All['clean_msg'] = df_All['clean_msg'].replace('\t', ' ', regex=True)

###  2 Marks-> b) Generate vectors for the given stories

Create a representation of text, convert it into vectors (numbers)


**Use any one** of the following algorithms for this task :

* Countvectorizer or
* TFIDFVectorizer or
* Word2Vec (The word2vec bin file (AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD) can be downloaded as a part of setup  )
  * perform sentence level tokenization and word level tokenization for the given stories

    **Example of sentences as list of words:**<br/>
    **Before:** ['This is a sentence .' , ' Another sentence']<br/>
    **After:** ['This', 'is' ,'a', 'sentence' , ' . ' , ' Another ', ' sentence ' ]
 * Assign the respective label associated for each vector representation of the extracted word

References Documents:

1.   [Countvectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)
2.  [TFIDFVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)

In [18]:
df_All.head()

,Story,Author,sentence_length,clean_text,unique_word_length,avg_sentence_length,clean_msg
0,"HOW THE WHALE GOT HIS THROAT IN the sea, once ...",Rudyard Kipling,34,"[whale, get, throat, sea, upon, time, best, be...",443,13.029412,whale get throat sea upon time best beloved wh...
1,HOW THE CAMEL GOT HIS HUMP NOW this is the nex...,Rudyard Kipling,36,"[camel, get, hump, next, tale, tell, camel, ge...",452,12.555556,camel get hump next tale tell camel get big hu...
2,HOW THE RHINOCEROS GOT HIS SKIN ONCE upon a ti...,Rudyard Kipling,34,"[rhinoceros, get, skin, upon, time, uninhabite...",376,11.058824,rhinoceros get skin upon time uninhabited isla...
3,HOW THE LEOPARD GOT HIS SPOTS IN the days when...,Rudyard Kipling,94,"[leopard, get, spots, day, everybody, start, f...",947,10.074468,leopard get spots day everybody start fair bes...
4,THE ELEPHANT’S CHILD IN the High and Far-Off T...,Rudyard Kipling,78,"[elephant, child, high, time, elephant, best, ...",1126,14.435897,elephant child high time elephant best beloved...

In [66]:
# YOUR CODE HERE (HINT: Convert to numpy array if needed)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

tfidfvectorizer = TfidfVectorizer()
X = tfidfvectorizer.fit_transform(df_All['clean_msg'])
y = labelEncoder.fit_transform(df_All['Author'])

print('-------------TfidfVectorizer------------------------')
tfidf_stats = test_models(X, y)
for stat in tfidf_stats:
  print(stat)

-------------TfidfVectorizer------------------------
Accuracy(in %): DecisionTreeClassifier() Train Accuracy 1.0  Test Accuracy 1.0
Accuracy(in %): KNeighborsClassifier(n_neighbors=8) Train Accuracy 0.625  Test Accuracy 0.7142857142857143
Accuracy(in %): SGDClassifier() Train Accuracy 1.0  Test Accuracy 1.0
Accuracy(in %): SVC(kernel='linear') Train Accuracy 1.0  Test Accuracy 1.0
Accuracy(in %): LogisticRegression() Train Accuracy 1.0  Test Accuracy 0.7142857142857143

###  1 Mark -> c) Is stop word removal necessary in the context of author identification? Your thoughts below?

##**Stage 4:** Classification :

### Expected accuracy is above 85%

### 2 Marks -> Perform a classification using either features obtained from Stage2 or Stage3

In [67]:
countVectorizer = CountVectorizer()

X = countVectorizer.fit_transform(df_All['clean_msg'])
y = labelEncoder.fit_transform(df_All['Author'])

print('-------------CountVectorizer------------------------')
countVectorizer_stats = test_models(X, y);
for stat in countVectorizer_stats:
  print(stat)

-------------CountVectorizer------------------------
Accuracy(in %): DecisionTreeClassifier() Train Accuracy 1.0  Test Accuracy 1.0
Accuracy(in %): KNeighborsClassifier(n_neighbors=8) Train Accuracy 0.7083333333333334  Test Accuracy 0.8571428571428571
Accuracy(in %): SGDClassifier() Train Accuracy 1.0  Test Accuracy 1.0
Accuracy(in %): SVC(kernel='linear') Train Accuracy 1.0  Test Accuracy 1.0
Accuracy(in %): LogisticRegression() Train Accuracy 1.0  Test Accuracy 1.0