<a href="https://colab.research.google.com/github/vikramvundyala/python_AI-ML/blob/main/U2_MH1_AuthorIdentification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Problem Statement

The problem is to identify the author of a  book from a given list of possible authors.

## Learning Objectives

At the end of the experiment, you will be able to:

* Use NLTK package
* Extract handcrafted features
* Preprocess the text
* Write an algorithm to identify the author of a given book

In [ ]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="854" height="480" controls>
  <source src="https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/Walkthrough/authoridentification.mp4" type="video/mp4">
</video>
""")

## Background

Author identification is the task of identifying the author of a given text. It can be considered as a typical classification problem, where a set of books with known authors are used for training. The aim is to automatically determine the corresponding author of an anonymous text.

## Grading = 10 Marks

## Setup Steps

In [ ]:
#@title Run this cell to complete the setup for this Notebook

from IPython import get_ipython
ipython = get_ipython()

notebook="U2_MH1_AuthorIdentification" #name of the notebook
Answer = "This notebook is graded by mentors on the day of hackathon"
def setup():
    ipython.magic("sx wget https://cdn.talentsprint.com/talentsprint1/archives/sc/aiml/experiment_related_data/AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.rar")
    ipython.magic("sx unrar e /content/AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.rar")
    print ("Setup completed successfully")
    return

setup()

Setup completed successfully

### NOTE: You are allowed to use ML libraries such as Sklearn, NLTK, etc wherever applicable

### Downloading the required nltk Packages before moving ahead

In [ ]:
import nltk
nltk.download('gutenberg')
nltk.download('punkt')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

## **Stage 1:** Dataset Preparation

### 1 Marks -> Ensure you appropriately split the multiple short stories for the below-mentioned authors, Which will be your training data.

**1.** Before moving ahead choose two authors based on your team-number allocation: <br/>


Team=1,5,9,13,17,21,25,29  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Author-A Vs Author-B <br />
Team=2,6,10,14,18,22,26,30 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Author-B Vs Author-C <br />
Team=3,7,11,15,19,23,27,31 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Author-C Vs Author-D <br />
Team=4,8,12,16,20,24,28,32 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           Author-D Vs Author-E <br />



**2.** Link to the short stories collection of each author for your problem: <br />

*   Author-A -> Rudyard Kipling   [Short Stories Collection](http://www.gutenberg.org/files/2781/2781-0.txt) &nbsp;&nbsp;
*   Author-B -> Anton Chekhov [Short Stories Collection](http://www.gutenberg.org/files/1732/1732-0.txt) &nbsp;&nbsp;
*   Author-C -> Guy De Maupassant [Short Stories Collection](http://www.gutenberg.org/cache/epub/21327/pg21327.txt)&nbsp;&nbsp;
*   Author-D -> Mark Twain [Short Stories Collection](http://www.gutenberg.org/files/245/245-0.txt)&nbsp;&nbsp;
*   Author-E -> Saki [Short Stories Collection](http://www.gutenberg.org/files/1477/1477-0.txt)&nbsp;&nbsp;

**Hint for downloading raw text from Gutenberg :**  Refer to the section "Electronic Books" in the following  [link](https://www.nltk.org/book/ch03.html) for the instructions.



**Hint for finding the index of a text:**   You may use `raw.find()` and `raw.rfind()` in the same [link](https://www.nltk.org/book/ch03.html) to find the appropriate index of the start and end location

**Hint for splitting the multiple stories:** Split the stories using long space (white space character)

**Note:** Ignore the table of contents section from the given stories

In [3]:
# YOUR CODE HERE for downloading and splitting the multiple stories of respective authors which are allocated to you

from urllib import request
from nltk.tokenize import sent_tokenize
import re
import pandas as pd

url = "https://www.gutenberg.org/files/2781/2781-0.txt"
response = request.urlopen(url)
raw_A = response.read().decode('utf8')

text_split_A = re.split(r'[\r\n\r\n\r\n\r\n\r\n]', raw_A)
len(text_split_A)
df = pd.DataFrame({'Paragraphs': [para.strip() for para in text_split_A if para.strip() != '']})
stories_list_A = df.iloc[17:29]

In [4]:
stories_list_A

                           Paragraphs
17       HOW THE WHALE GOT HIS THROAT
18         HOW THE CAMEL GOT HIS HUMP
19    HOW THE RHINOCEROS GOT HIS SKIN
20      HOW THE LEOPARD GOT HIS SPOTS
21               THE ELEPHANT’S CHILD
22  THE SING-SONG OF OLD MAN KANGAROO
23    THE BEGINNING OF THE ARMADILLOS
24   HOW THE FIRST LETTER WAS WRITTEN
25          HOW THE ALPHABET WAS MADE
26  THE CRAB THAT PLAYED WITH THE SEA
27     THE CAT THAT WALKED BY HIMSELF
28         THE BUTTERFLY THAT STAMPED

In [6]:
story_Array = []
i =29;
for outer_idx, outer_row in df.iloc[17:29].iterrows():
    story_chunk = []
    for inner_idx, inner_row in df.iloc[i:].iterrows():
        if outer_row["Paragraphs"].strip() == inner_row["Paragraphs"].strip():
            break
        story_chunk.append(inner_row["Paragraphs"])
        i += 1
    if(len(story_chunk)>0):
     story_Array.append(story_chunk)

df_A = pd.DataFrame({'Story': [s for s in story_Array if s != '']})
len(story_Array)

11

In [8]:
df_A['Author'] = 'Rudyard Kipling'
df_A.head()

                                               Story           Author
0  [HOW THE WHALE GOT HIS THROAT, IN the sea, onc...  Rudyard Kipling
1  [HOW THE CAMEL GOT HIS HUMP, NOW this is the n...  Rudyard Kipling
2  [HOW THE RHINOCEROS GOT HIS SKIN, ONCE upon a ...  Rudyard Kipling
3  [HOW THE LEOPARD GOT HIS SPOTS, IN the days wh...  Rudyard Kipling
4  [THE ELEPHANT’S CHILD, IN the High and Far-Off...  Rudyard Kipling

In [9]:
url_1 = "https://www.gutenberg.org/files/1732/1732-0.txt"
response_B = request.urlopen(url_1)
raw_B = response_B.read().decode('utf8')

text_split_B = re.split(r'[\r\n\r\n\r\n\r\n\r\n]', raw_B)
len(text_split_B)
df_1 = pd.DataFrame({'Paragraphs': [para.strip() for para in text_split_B if para.strip() != '']})

In [14]:
df_1.iloc[17:38]

                     Paragraphs
17           THE SCHOOLMISTRESS
18          A NERVOUS BREAKDOWN
19                       MISERY
20                    CHAMPAGNE
21            AFTER THE THEATRE
22               A LADY’S STORY
23                     IN EXILE
24           THE CATTLE-DEALERS
25                       SORROW
26             ON OFFICIAL DUTY
27    THE FIRST-CLASS PASSENGER
28               A TRAGIC ACTOR
29              A TRANSGRESSION
30                    SMALL FRY
31                  THE REQUIEM
32           IN THE COACH-HOUSE
33                  PANIC FEARS
34                      THE BET
35    THE HEAD-GARDENER’S STORY
36                 THE BEAUTIES
37  THE SHOEMAKER AND THE DEVIL

In [19]:
df_1.iloc[17:38]
story_Array_B = []
i =38;
for outer_idx, outer_row in df_1.iloc[17:38].iterrows():
    story_chunk = []
    for inner_idx, inner_row in df_1.iloc[i:].iterrows():
        if outer_row["Paragraphs"].strip() == inner_row["Paragraphs"].strip():
            break
        story_chunk.append(inner_row["Paragraphs"])
        i += 1
    if(len(story_chunk)>0):
     story_Array_B.append(story_chunk)

In [21]:
len(story_Array_B)
df_B = pd.DataFrame({'Story': [s for s in story_Array_B if s != '']})
df_B['Author'] = 'Anton Chekhov'
df_B.head()

                                               Story         Author
0  [THE SCHOOLMISTRESS, AT half-past eight they d...  Anton Chekhov
1  [A NERVOUS BREAKDOWN, A MEDICAL student called...  Anton Chekhov
2  [MISERY, “To whom shall I tell my grief?”, THE...  Anton Chekhov
3  [CHAMPAGNE, A WAYFARER’S STORY, IN the year in...  Anton Chekhov
4  [AFTER THE THEATRE, NADYA ZELENIN had just com...  Anton Chekhov

In [22]:
df_All = pd.concat([df_A, df_B], ignore_index=True)

                                               Story           Author
0  [HOW THE WHALE GOT HIS THROAT, IN the sea, onc...  Rudyard Kipling
1  [HOW THE CAMEL GOT HIS HUMP, NOW this is the n...  Rudyard Kipling
2  [HOW THE RHINOCEROS GOT HIS SKIN, ONCE upon a ...  Rudyard Kipling
3  [HOW THE LEOPARD GOT HIS SPOTS, IN the days wh...  Rudyard Kipling
4  [THE ELEPHANT’S CHILD, IN the High and Far-Off...  Rudyard Kipling

In [27]:
df_All.shape
df_All[0:1]['Story']

0    [HOW THE WHALE GOT HIS THROAT, IN the sea, onc...
Name: Story, dtype: object

## **Stage 2**: Experiment with Handcrafted features representation
Extract Handcrafted features for the obtained short stories from **Stage-1**

**Stylometry:**

Each person has a unique vocabulary, sometimes rich, sometimes limited. Although a larger vocabulary is usually associated with literary quality, this is not always the case. Ernest Hemingway is famous for using a surprisingly small number of different words in his writing, which did not prevent him from winning the Nobel Prize for Literature in 1954.

Some people write in short sentences, while others prefer long blocks of text consisting of many clauses. No two people use semicolons, em-dashes, and other forms of punctuation in the same way.




**You may explore the following ways to analyze the text and generate handcrafted features by searching text in a probing way:**

a)  Could the style of punctuation usage help as a handcrafted feature? Both by those who follow punctuations and by those who don't? Interesting [link](https://qwiklit.com/2014/03/05/top-10-authors-who-ignored-the-basic-rules-of-punctuation/)

b) The same word can sometimes be used in different contexts repeatedly by different authors. Could this fact be converted as a handcrafted feature? [link](https://www.nltk.org/book/ch01.html)

c) The above two are merely examples; As you might have noticed already the NLTK book [link](https://www.nltk.org/book/) offers several methods of analyzing and understanding the text. Each of these analyses is in itself capable of being a handcrafted feature. **However for your evaluation a minimal set of useful handcrafted features which is helping you prove a classification of an is sufficient**

d) Could most common words be used to distinguish authors?  Refer "Counting Vocabulary" section of the [link](https://www.nltk.org/book/ch01.html)

e) How about using a count of most frequently used bi-gram, tri-grams, and using it to classify an author?

f) How about using the frequency histogram of the most frequently used words across the stories by a given author a useful feature?

The limit here is endlessly limited only by your imagination, and of course your accuracy! :)

### 1 Marks ->  a) List 6 handcrafted features to distinguish author stories.

In [1]:
# For eg:
# 1. UniqueWords
# 2. AvgSentLength
# List the other handcrafted features here

from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
import string

stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

def clean_text(text: str) :
  words = word_tokenize(text)
  words = [word.lower() for word in words if word.isalpha()]
  words = [word for word in words if word not in stop_words]
  words = [word for word in words if word not in punctuation]
  return words


df_All['sentence_length'] = df_All['Story'].apply(lambda x: len(sent_tokenize(x)))
df_All['clean_text'] = df_All['Story'].apply(lambda x: clean_text(x))
df_All['unique_word_length'] = df_All['clean_text'].apply(lambda x: len(word_tokenize(x)))

avg = df_All["unique_word_length"].sum() / len(df_All)
df_All['avg_word_length'] = avg

# YOUR CODE HERE

LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

###  2 Marks -> b) Write functions for any 4 of the above 6 handcrafted features and label your authors accordingly.

- Get any 4 hand crafted features from the above listed 6 hand-crafted features for every story obtained from **stage-1**.
- Identify your target variable as an author and label them accordingly.

In [ ]:
# Stories_list    UniqueWords    AvgSentLength     Label
#     1               x1               x2            y

# YOUR CODE HERE

##**Stage 3:** Experiment with Text processing and representation:
Extract features using TFIDF or CountVectorizer or Word2vec for the obtained short stories from **Stage-1**

### 1 Mark -> a) Performing basic cleanup operations such as removing the newline characters and removing trailing spaces

**For example,** Your sentence looks as follows \[' This is a sentence\n\r. Another sentence \n'].

After newline removal from the above example, your sentence will look like \['This is a sentence. Another sentence'].

 In order to do this, you can try using a combination of split() and join()

In [ ]:
# YOUR CODE HERE

###  2 Marks-> b) Generate vectors for the given stories

Create a representation of text, convert it into vectors (numbers)


**Use any one** of the following algorithms for this task :

* Countvectorizer or
* TFIDFVectorizer or
* Word2Vec (The word2vec bin file (AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD) can be downloaded as a part of setup  )
  * perform sentence level tokenization and word level tokenization for the given stories

    **Example of sentences as list of words:**<br/>
    **Before:** ['This is a sentence .' , ' Another sentence']<br/>
    **After:** ['This', 'is' ,'a', 'sentence' , ' . ' , ' Another ', ' sentence ' ]
 * Assign the respective label associated for each vector representation of the extracted word

References Documents:

1.   [Countvectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)
2.  [TFIDFVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)

In [ ]:
# YOUR CODE HERE (HINT: Convert to numpy array if needed)

###  1 Mark -> c) Is stop word removal necessary in the context of author identification? Your thoughts below?

In [ ]:
# YOUR ANSWER IN TEXT

##**Stage 4:** Classification :

### Expected accuracy is above 85%

### 2 Marks -> Perform a classification using either features obtained from Stage2 or Stage3

In [ ]:
# YOUR CODE HERE

# Further Ideas for exploration after the hackathon:

**Statistical analysis** of text using NLP, by analysis meaning of sentences, feature based grammars and analyzing structure of sentences!

reference: www.nltk.org/book